export const mockSubscriptions = [
  {
    id: '1',
    name: 'Netflix',
    price: 15.99,
    billingCycle: 'monthly',
    status: 'active',
    icon: '🎬',
    category: 'Entertainment',
    startDate: '2024-01-15',
    nextBilling: '2024-02-15',
  },
  {
    id: '2',
    name: 'Spotify Premium',
    price: 9.99,
    billingCycle: 'monthly',
    status: 'active',
    icon: '🎵',
    category: 'Music',
    startDate: '2023-12-10',
    nextBilling: '2024-02-10',
  },
  {
    id: '3',
    name: 'Adobe Creative Cloud',
    price: 52.99,
    billingCycle: 'monthly',
    status: 'active',
    icon: '🎨',
    category: 'Productivity',
    startDate: '2023-11-20',
    nextBilling: '2024-02-20',
  },
  {
    id: '4',
    name: 'Amazon Prime',
    price: 14.99,
    billingCycle: 'monthly',
    status: 'active',
    icon: '📦',
    category: 'Shopping',
    startDate: '2024-01-01',
    nextBilling: '2024-02-01',
  },
  {
    id: '5',
    name: 'Disney+',
    price: 10.99,
    billingCycle: 'monthly',
    status: 'paused',
    icon: '🏰',
    category: 'Entertainment',
    startDate: '2023-10-15',
    nextBilling: null,
  },
  {
    id: '6',
    name: 'Microsoft 365',
    price: 6.99,
    billingCycle: 'monthly',
    status: 'cancelled',
    icon: '💼',
    category: 'Productivity',
    startDate: '2023-09-01',
    nextBilling: null,
  },
]

export const mockRegionalServices = [
  {
    id: 'r1',
    name: 'Airtel Recharge',
    type: 'mobile',
    icon: '📱',
    plans: [
      { name: 'Basic Plan', price: 199, validity: '28 days' },
      { name: 'Premium Plan', price: 399, validity: '56 days' },
    ],
  },
  {
    id: 'r2',
    name: 'Jio Recharge',
    type: 'mobile',
    icon: '📱',
    plans: [
      { name: 'Basic Plan', price: 149, validity: '28 days' },
      { name: 'Premium Plan', price: 299, validity: '56 days' },
    ],
  },
  {
    id: 'r3',
    name: 'Vodafone Recharge',
    type: 'mobile',
    icon: '📱',
    plans: [
      { name: 'Basic Plan', price: 179, validity: '28 days' },
      { name: 'Premium Plan', price: 349, validity: '56 days' },
    ],
  },
  {
    id: 'r4',
    name: 'Hotstar',
    type: 'ott',
    icon: '📺',
    plans: [
      { name: 'Monthly', price: 299 },
      { name: 'Yearly', price: 1499 },
    ],
  },
  {
    id: 'r5',
    name: 'Zee5',
    type: 'ott',
    icon: '📺',
    plans: [
      { name: 'Monthly', price: 99 },
      { name: 'Yearly', price: 999 },
    ],
  },
]

export const mockBundles = [
  {
    id: 'b1',
    name: 'Entertainment Bundle',
    description: 'Netflix + Disney+ + Prime Video',
    originalPrice: 41.97,
    discountedPrice: 29.99,
    discount: 28,
    subscriptions: ['Netflix', 'Disney+', 'Prime Video'],
  },
  {
    id: 'b2',
    name: 'Music & Podcast Bundle',
    description: 'Spotify + Apple Music + Audible',
    originalPrice: 32.97,
    discountedPrice: 24.99,
    discount: 24,
    subscriptions: ['Spotify', 'Apple Music', 'Audible'],
  },
  {
    id: 'b3',
    name: 'Productivity Suite',
    description: 'Microsoft 365 + Adobe CC + Notion',
    originalPrice: 69.97,
    discountedPrice: 49.99,
    discount: 29,
    subscriptions: ['Microsoft 365', 'Adobe CC', 'Notion'],
  },
]

